# clazyfiler configuration file
# Place this file at ~/.config/clazyfiler/config.toml

[keymaps]
# Key bindings for various actions (HashMap-based flexible mapping)
"q" = "quit"        # Quit the application
"k" = "up"          # Move selection up (vim-style)
"Up" = "up"         # Move selection up (arrow key)
"j" = "down"        # Move selection down (vim-style)
"Down" = "down"     # Move selection down (arrow key)
"h" = "back"        # Go to parent directory (vim-style)
"Left" = "back"     # Go to parent directory (arrow key)
"l" = "select"      # Enter directory/select file (vim-style)
"Right" = "select"  # Enter directory/select file (arrow key)
"Enter" = "select"  # Enter directory/select file
"Escape" = "back"   # Go back to parent directory
"r" = "refresh"     # Refresh file list
"F5" = "refresh"    # Refresh file list (F5 key)
"/" = "search"      # Enter search mode

# Search Mode Keys (automatically handled when in search mode):
# - Type any character to search
# - Backspace to delete last character  
# - Up/Down arrows to navigate results
# - Enter to select highlighted file and exit search
# - Escape to exit search mode

[ui]
# User interface settings
panel_width_ratio = 50      # Width ratio of panels (percentage)
show_borders = true         # Show borders around panels
show_hidden_files = false   # Display hidden files (starting with .)
file_list_margin = 1        # Margin around file list

[external_commands]
# External command integration
fuzzy_finder = "fzf"        # Fuzzy finder command
editor = "$EDITOR"          # Text editor (uses $EDITOR env var)
file_manager = "xdg-open"   # File manager for opening files

[general]
# General application settings
default_directory = "~"     # Default starting directory