# Alternative clazyfiler configuration
# Example showing different key mappings and settings

[keymaps]
# Arrow keys and common shortcuts (alternative mapping)
"q" = "quit"          # Quit the application
"Up" = "up"           # Use arrow keys instead of vim keys
"Down" = "down"       # Arrow down for selection
"Left" = "back"       # Arrow left to go back
"Right" = "select"    # Arrow right to enter/select
"Enter" = "select"    # Enter key for selection
"Backspace" = "back"  # Backspace to go back
"F5" = "refresh"      # F5 to refresh
"s" = "search"        # 's' key for search instead of '/'

# This configuration shows how to:
# - Use only arrow keys for navigation (no vim keys)
# - Use different keys for common actions (Backspace, 's' for search)
# - Customize the search trigger key

[ui]
# Minimal UI settings
panel_width_ratio = 70      # Wider panels
show_borders = false        # Clean look without borders
show_hidden_files = true    # Show all files including hidden
file_list_margin = 0        # No margin for more space

[external_commands]
# Different external tools
fuzzy_finder = "sk"         # Use skim instead of fzf
editor = "nvim"             # Neovim as editor
file_manager = "thunar"     # Thunar file manager

[general]
# Start in home directory
default_directory = "~"